version = 0.1
[default.deploy.parameters]
stack_name = "sam-serverless-python"
resolve_s3 = true
s3_prefix = "sam-serverless-python"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Table=\"Activities\" Region=\"ap-southeast-1\" AWSEnv=\"AWS\""
image_repositories = []

